### ISSUE TITLE
Mattermost 3.5で実行するとJsonMappingExceptionが発生する

### ISSUE THREAD

**Issue by maruTA-bis5** [tsyki/mattermost-channel-add-checker#21]
Mattermost 3.5でいくつかのAPIが返す値が変わっているようで、チャンネル取得時に以下の通りJsonMappingExceptionが発生します。
```
$ java -jar mattermost-channel-add-checker-jar-with-dependencies.jar
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: [{"id":"pkrrnxe7qpfzbyu41nyed5pb9r","create_at":1473076332482,"update_at":1473076332482,"delete_at":0,"team_id":"4y6g1x1qrtntfb3h9txc39izuc","type":"O","display_name":"new-channel","name":"new-channel","header":"","purpose":"","last_post_at":1479880384355,"total_msg_count":31,"extra_update_at":1479880384134,"creator_id":"h94q1idpn7gippiwtzec45wcaa"},{"id":"64p8ixo3mfbu9ey99a9a1sefjh","create_at":1464658270987,"update_at":1464658270987,"delete_at":0,"team_id":"4y6g1x1qrtntfb3h9txc39izuc","type":"O","display_name":"Off-Topic","name":"off-topic","header":"","purpose":"","last_post_at":1475416951719,"total_msg_count":12,"extra_update_at":1472614290212,"creator_id":""},{"id":"bc6atp7z13dkmd7j6zui19iyge","create_at":1464658304254,"update_at":1464658304254,"delete_at":0,"team_id":"4y6g1x1qrtntfb3h9txc39izuc","type":"O","display_name":"timeline","name":"timeline","header":"","purpose":"","last_post_at":1479881685133,"total_msg_count":64,"extra_update_at":1479880379081,"creator_id":"h94q1idpn7gippiwtzec45wcaa"},{"id":"rpxh1jsfhiywfq4s9ygqg6135c","create_at":1464658270980,"update_at":1464658270980,"delete_at":0,"team_id":"4y6g1x1qrtntfb3h9txc39izuc","type":"O","display_name":"Town Square","name":"town-square","header":"","purpose":"","last_post_at":1475416017470,"total_msg_count":23,"extra_update_at":1472614290201,"creator_id":""}]; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
        at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1233)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1121)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1074)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:895)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:348)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
        at tsyki.mattermost.driver.MattermostWebDriver.parseJson(MattermostWebDriver.java:214)
        at tsyki.mattermost.driver.MattermostWebDriver.getChannels(MattermostWebDriver.java:268)
        at tsyki.mattermost.driver.MattermostWebDriver.getJoinedChannels(MattermostWebDriver.java:250)
        at tsyki.mattermost.driver.MattermostWebDriver.getAllChannels(MattermostWebDriver.java:226)
        at tsyki.mattermost.driver.MattermostWebDriver.getAllPublicChannels(MattermostWebDriver.java:238)
        at tsyki.mattermost.ChannelCreateChecker.run(ChannelCreateChecker.java:127)
        at tsyki.mattermost.ChannelCreateChecker.main(ChannelCreateChecker.java:86)
```

- 環境
    - Mattermost 3.5.0
    - Ubuntu 16.04.1 LTS
    - OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
    - Apache Maven 3.3.9

**Comment by tsyki** [comment]
3.4では以下のようにMapになっているが、3.5ではListになっている  
* 3.4
````
{
    "channels": [
        {
            "create_at": 1476253187585, 
            ...
            "update_at": 1476253187585
        }, 
        {
            "create_at": 1459339137651, 
            "creator_id": "",
            ... 
````
* 3.5
````
[
    {
        "create_at": 1480059997567, 
        ...
        "update_at": 1480059997567
    }, 
    {
        "create_at": 1480059788226, 
        ...
````
